config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :properties do
    resources :transactions, only: %i[create update edit]
  end
  resources :transactions, only: :destroy
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "components", to: "pages#components"
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :user
  has_many :transactions
  has_one_attached :photo
  # validates :photo, attached: true, content_type: ['image/png', 'image/jpeg']
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :address, presence: true
  validates :bedrooms, presence: true
  validates :property_type , presence:true


  def total_profit
    # transactions.map do |transaction|
    #   transaction.cash_flow_type == "Revenue" ? transaction.amount : -transaction.amount
    # end.sum
    @month_total = 0
    transactions.each do |transaction|
      if transaction.date.month == Time.now.month && transaction.date.year == Time.now.year
        if transaction.cash_flow_type == "Revenue"
          @month_total += transaction.amount.round
        else
          @month_total -= transaction.amount.round
        end
      end
    end
    return @month_total
  end


  def profitable?
    if total_profit.positive?
      return "fa-solid fa-caret-up text-success"
    elsif total_profit.zero?
      return "fa-solid fa-caret-right text-warning"
    else
      return "fa-solid fa-caret-down text-danger"
    end
  end

  CATEGORIES = ["Unit", "House"]
end

app/controllers/properties_controller.rb
require_relative "../services/fetch_price_service"

class PropertiesController < ApplicationController
  def index
    @properties = Property.all
    @property = Property.new
    @markers = @properties.geocoded.map do |property|
      {
        lat: property.latitude,
        lng: property.longitude
      }
    end
  end

  def show
    @properties = Property.all
    @property = Property.find(params[:id])
    @transactions = @property.transactions.sort_by(&:date).reverse
    if params[:filter].present?
      if params[:filter] == "Show All"
        @transactions = @property.transactions.sort_by(&:date).reverse
      else
        @transactions = @property.transactions.where("category ILIKE ?", "%#{params[:filter]}%")
      end
    end
    # @past_transactions = @property.transactions.past
    # @future_transactions = @property.transactions.future
    @suburb_overview = FetchPriceService.new(@property).call
    # @suburb_number = FetchPriceService.new(@property).number
    # date categorization of transactions
    @last = []
    @current = []
    @month = []
    # @month_revenues = []
    # @month_expenses = []
    @month_revenue = 0
    @month_expense = 0
    @month_total = 0
    @transactions.each do |transaction|
      if transaction.date < "2022-07-01".to_date && transaction.date > "2021-06-30".to_date
        @last << transaction
      end
      if transaction.date > "2022-06-30".to_date
        @current << transaction
      end
      if transaction.date.month == Time.now.month && transaction.date.year == Time.now.year
        @month << transaction
        if transaction.cash_flow_type == "Revenue"
          @month_revenue += transaction.amount.round
          @month_total += transaction.amount.round
          # @month_revenues << transaction
        else
          @month_expense += transaction.amount.round
          @month_total -= transaction.amount.round
          # @month_expenses << transaction
        end
      end
    end
    @marker = { lat: @property.latitude, lng: @property.longitude }
    @average = Transaction.expenses.select(:category, (:amount)).group(:category).sum(:amount).inject({}) { |h, (k, v)| h[k] = (v / @properties.count).round(); h }
    @single =  @property.transactions.expenses.select(:category, :amount).group(:category).sum(:amount)
    # @single_month = @month_expenses.select(:category, :amount).group(:category).sum(:amount)
    @revenue = @property.transactions.revenues.sum(:amount)
    @expense = @property.transactions.expenses.sum(:amount)
  end

  def new
    @property = Property.new
  end

  def create
    @property = Property.new(property_params)
    @property.user = current_user
    if @property.save
      redirect_to property_path(@property), notice: "Property Created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def property_params
    params.require(:property).permit(:bedrooms, :address, :property_type, :photo)
  end
end

app/views/properties/_addpropertyform.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content" id="modal-holder">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add New Property</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <%= simple_form_for(@property, html: { class: "w-100" }) do |f| %>
        <div class="modal-body">
          <div class="row mb-4">
            <div class="col-6">
              <%= f.input :address
                # input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                # wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
              %>
            </div>
            <div class="col-6">
              <%= f.input :bedrooms, collection: (1..5), include_blank: false %>
            </div>
          </div>
          <%= f.input :property_type, :collection => %w[Unit House], as: :radio_buttons, wrapper_html: { class: "mb-4"},
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'category-wrapper',
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector'},
                collection: Property::CATEGORIES %>
          <%= f.input :photo, as: :file, wrapper_html: { class: "mb-4" } %>
        </div>
        <div class="modal-footer justify-content-center">
          <%= f.submit class: "btn btn-primary w-50 rounded-pill", value: "Create", id: "create-button"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/properties/_dashboardnavbar.html.erb
<section class="dashboard-header">
  <div class="dashboard-container">
    <div class="dashboard-row">
      <div class="col-lg-4 d-flex">
        <h2 class="dash-property text-start" data-controller="typed-js" data-typed-js-name-value="<%= current_user.first_name %>"></h2>
      </div>
      <div class="col-lg-4">
        <h2 class="dash-property2">Properties Summary</h2>
      </div>
      <div class="col-lg-4 d-flex align-items-center justify-content-end">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" id="add-property-button">
          +Add Property
        </button>
      </div>
    </div>

  </div>

    <%# <p><span data-controller="typed-js"></span></p> %>

</section>

app/views/properties/_form.html.erb
<div>
  <div class="container h-100 col-6">
    <div class="h-100 d-flex flex-column align-items-center justify-content-center">
      <div class="w-100 rounded bg-secondary bg-opacity-50 p-5 shadow-lg">
        <h1 class="mb-4 text-decoration-underline">Add a Property</h1>
        <%= simple_form_for(@property, html: { class: "w-100" }) do |f| %>
          <div class="row mb-4">
            <div class="col-6">
              <%= f.input :address
                # input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                #  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
              %>
            </div>
            <div class="col-6">
              <%= f.input :bedrooms, collection: (1..5), include_blank: false %>
            </div>
          </div>
          <%= f.input :property_type, :collection => %w[Unit House], as: :radio_buttons, wrapper_html: { class: "mb-4"},
                collection_wrapper_tag: 'div',
                collection_wrapper_class: 'category-wrapper',
                item_wrapper_class: 'category-item',
                input_html: {class: 'category-selector'},
                collection: Property::CATEGORIES %>
          <%= f.input :photo, as: :file, wrapper_html: { class: "mb-4" } %>
          <%= f.submit class: "btn btn-primary w-50 rounded-pill" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/properties/_indexcards.html.erb
  <div class="card-container">
    <% @properties.each do |property| %>
    <%= link_to property_path(property), class: "index-card" do %>
      <img src="https://i2.au.reastatic.net/1000x750-format=webp/11cec2902a7318a9a7ece6decc7058aea782bc3b2fd99dfcbcd13f0e6458bc67/image.jpg" />
      <div class="index-card-product-infos">
        <h2><%= property.address %>, <%= property.suburb %>, <%= property.state %></h2>
        <p>Product description with <strong>relevant info</strong> only.</p>
      </div>
    <%end%>
  <%end%>
  </div>


  <div class="card-container">
    <% @properties.each do |property| %>
      <%= link_to property_path(property), class: "index-card" do %>
        <%= cl_image_tag property.photo.key %>
        <div class="index-card-product-infos">
          <h2><%= property.address %></h2>
          <p>Product description with <strong>relevant info</strong> only.</p>
        </div>
      <%end%>
    <%end%>
  </div>
</div>

app/views/properties/_key_statistics.html.erb
<div class="row overviewGutter">
  <div class="col-md-4">
    <div class="panel">
      <div class="statsOverview--panel">
        <div class="statsOverview--header">
          <p class="statsOverview--headerIn">
            IN
          </p>
          <p class="statsOverview--headerInPercentage">
            <i class="fa fa-level-up-alt"></i>
            <%# <span>23%</span> %>
          </p>
        </div>

        <div class="statsOverview--body">
          <div class="row">
            <div class="col-8">
              <p class="statsOverview--rangeIn">Monthly</p>
              <h3 class="statsOverview--label">Revenue</h3>
              <p class="statsOverview--dollarIn">$<%= @month_revenue %></p>
            </div>
            <div class="col-4">
              <i class="green fa-solid fa-money-bill-trend-up"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel">
      <div class="statsOverview--panel">
        <div class="statsOverview--header">
          <p class="statsOverview--headerOut">
            OUT
          </p>
          <p class="statsOverview--headerOutPercentage">
            <i class="fa fa-level-down-alt"></i>
            <%# <span>10%</span> %>
          </p>
        </div>

        <div class="statsOverview--body">
          <div class="row">
            <div class="col-8">
              <p class="statsOverview--rangeOut">Monthly</p>
              <h3 class="statsOverview--label">Expenses</h3>
              <p class="statsOverview--dollarOut">$<%= @month_expense %></p>
            </div>
            <div class="col-4">
              <i class="fa-solid fa-money-bill-trend-up" id="moneyflip"></i>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <% if @month_total < 0 %>
    <div class="col-md-4">
      <div class="panel">
        <div class="statsOverview--panel">
          <div class="statsOverview--header">
            <p class="statsOverview--headerTotal dark-red">
              TOTAL
            </p>
            <p class="statsOverview--headerTotalPercentage dark-red-background">
              <i class="fa-solid fa-hand-holding-dollar"></i>
              <%# <span>23%</span> %>
            </p>
          </div>

          <div class="statsOverview--body">
            <div class="row">
              <div class="col-8">
                <p class="statsOverview--rangeTotal dark-red">Monthly</p>
                <h3 class="statsOverview--label">Total</h3>
                <p class="statsOverview--dollarTotal dark-red">-$<%= @month_total * -1 %></p>
              </div>
              <div class="col-4">
                <i class="fa-solid fa-money-bill-transfer dark-red"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% else %>
    <div class="col-md-4">
      <div class="panel">
        <div class="statsOverview--panel">
          <div class="statsOverview--header">
            <p class="statsOverview--headerTotal dark-green">
              TOTAL
            </p>
            <p class="statsOverview--headerTotalPercentage dark-green-background">
              <i class="fa-solid fa-hand-holding-dollar"></i>
              <%# <span>23%</span> %>
            </p>
          </div>

          <div class="statsOverview--body">
            <div class="row">
              <div class="col-8">
                <p class="statsOverview--rangeTotal dark-green">Monthly</p>
                <h3 class="statsOverview--label">Total</h3>
                <p class="statsOverview--dollarTotal dark-green">$<%= @month_total %></p>
              </div>
              <div class="col-4">
                <i class="fa-solid fa-money-bill-transfer dark-green"></i>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/properties/_property.html.erb
<%= link_to property_path(property), class: "index-property-card" do %>

  <div class="index-property-image" style="background-image: linear-gradient(rgba(0,0,0, 0.1), rgba(0,0,0,0.1)), url(<%= cl_image_path property.photo.key %>)">

    <div class="property-address">
      <% if property.property_type == "unit" %>
        <i class="fa-solid fa-building text-white "></i>
      <% else %>
        <i class = "fa-solid fa-house text-white "></i>
      <% end %>
      <div>
        <h3><%= property.address.split(",")[0] %></h3>
        <p><%= property.address.split(",")[1] %> • <%= property.address.split(",")[2]%></p>
      </div>
    </div>

    <div class="property-key-info">
      <div>
        <i class="<%= property.profitable? %>" id="money-icon"></i>
        <p>$ <%= property.total_profit.to_i %></p>
      </div>
      <div>
        <i class="fa-solid fa-bed text-warning text-white"></i>
        <p><%= property.bedrooms %></p>
      </div>
      <div>
        <i class="fa-solid fa-calendar text-white"></i>
        <p><%= rand(Date.civil(2022, 1, 1)..Date.civil(2022, 12, 31)).strftime("%d/%m/%y")%> - <%= rand(Date.civil(2023, 1, 1)..Date.civil(2023, 12, 31)).strftime("%d/%m/%y") %></p>
      </div>
    </div>

    <div class="blur-background"></div>

  </div>
<% end %>

app/views/properties/_propertycards.html.erb
<div class="wrapper bg-gray-400 antialiased text-gray-900">
  <div>

      <img src="https://source.unsplash.com/random/350x350" alt=" random imgee" class="w-full object-cover object-center rounded-lg shadow-md">

  <div class="relative px-4 -mt-16  ">
    <div class="bg-white p-6 rounded-lg shadow-lg">
      <div class="flex items-baseline">
        <span class="bg-teal-200 text-teal-800 text-xs px-2 inline-block rounded-full  uppercase font-semibold tracking-wide">
          New
        </span>
        <div class="ml-2 text-gray-600 uppercase text-xs font-semibold tracking-wider">
      2 baths  &bull; 3 rooms
    </div>
      </div>

      <h4 class="mt-1 text-xl font-semibold uppercase leading-tight truncate">A random Title</h4>

    <div class="mt-1">
      $1800
      <span class="text-gray-600 text-sm">   /wk</span>
    </div>
    <div class="mt-4">
      <span class="text-teal-600 text-md font-semibold">4/5 ratings </span>
      <span class="text-sm text-gray-600">(based on 234 ratings)</span>
    </div>
    </div>
  </div>

  </div>
</div>

app/views/properties/_propertynavbar.html.erb
<section class="dashboard-header">
  <div class="dashboard-container">
    <div class="dashboard-row">
      <div class="col-lg-4">
        <nav role="navigation" class="primary-navigation">
          <ul>
            <li class="show-property text-start"><div id="test8"><%=property.address%><a href="#" id="arrowdown">&dtrif;</a></div>
              <ul class="dropdown" id="addressdrop">
              <% @properties.each do |property| %>
                <li><%= link_to property.address, property_path(property) %></li>
              <% end %>
              </ul>
            </li>
          </ul>
        </nav>
        <%# <%= link_to properties_path, class: "d-flex align-items-center back-btn" do %>
          <%# <i class="fa-sharp fa-solid fa-arrow-left-long"></i> %>
          <%# <p>All Properties</p> %>
        <%# <% end %>

        <!--h2 class="dash-property text-start"><%= @property.address %></h2-->



      </div>

      <div class="col-lg-4">
        <div class="label-white">
          <div class="row">
            <ul class="nav nav-pills justify-content-center">
              <li class="nav-item">
                <a class="nav-link active" data-bs-toggle="pill" href="#transactions">Transactions</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-bs-toggle="pill" href="#graphs">Statistics</a>
              </li>
            </ul>
          </div>
        </div>
      </div>

      <div class="col-lg-4 d-flex align-items-center justify-content-end">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal" id="add-transaction-button">
          +Add Transaction
        </button>
      </div>
    </div>

  </div>
</section>

app/views/properties/_show_content.html.erb
<div class="container" data-controller="update-modal" data-submit-transaction-target="page">

  <div class="col-6" data-transactions-target="form">
    <%= render "transactions/modal" %>
  </div>

  <%= render "properties/key_statistics", property: @property %>

  <div class="transaction-container">
    <div class="tab-content">

      <div class="tab-pane container active" id="transactions">
        <div class="section">
          <%= render "properties/transactions" %>
        </div>
      </div>

      <div class="tab-pane container fade" id="graphs">
        <%= render "properties/graphs" %>
      </div>
    </div>
  </div>
</div>

app/views/properties/_suburb_summary.html.erb
<div class="suburbsum">
  <h2>Suburb Overview for <b><%= @suburb_overview["suburbName"]%></b></h2>
  <p>The percentage of the suburb that are renters: <b><%= @suburb_overview["data"]["renterPercentage"] %></b></p>
  <p> The most common age bracket living in the area: <b><%= @suburb_overview["data"]["mostCommonAgeBracket"] %></b></p>
  <p> <%= @suburb_overview["data"]["propertyCategories": @property.property_type]%></p>
</div>

app/views/properties/_transactions.html.erb
<div class="transaction-container">
  <div class="label">
    <div class="scroll-fade"></div>
    <div class="head">Transaction Summary</div>
    <div class="row">
      <div class="filter-dropdown">
        <%= form_with url: property_path(@property), method: :get do %>
        <%= select_tag :filter, options_for_select([ "Show All", "Maintenance", "Mortgage", "Rental Income", "Utilities", "Other" ], "Show All")
          %>
        <%= submit_tag "Filter", class: "filter-btn" %>
        <% end %>
      </div>
      <ul class="nav nav-pills justify-content-center">
        <% unless @last.empty? %>
          <li class="nav-item">
            <a class="nav-link" data-bs-toggle="pill" href="#last">Last Financial Year (21/22)</a>
          </li>
        <% end %>
        <li class="nav-item">
          <a class="nav-link active" data-bs-toggle="pill" href="#current">Current Financial Year (22/23)</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-bs-toggle="pill" href="#month"><%= Time.now.strftime("%B") %></a>
        </li>
      </ul>
    </div>
  </div>

  <div class="tab-content">


    <div class="tab-pane container fade" id="last">
      <div class="row justify-content-center">
        <div class="d-flex flex-row details">
          <div class="left-col">
            <h5>Date</h5>
          </div>
          <div class="desc-col text-center">
            <h5>Description</h5>
          </div>
          <div class="amnt-col">
            <h5>Amount</h5>
          </div>
        </div>
        <div class="summary-box">
          <div class="transaction-list">
            <% @last_count = 0 %>
            <% if @last.empty? %>
              <div class="no-data">
                There is no data recorded for this time period
              </div>
            <% else %>
              <% @last.each do |transaction| %>
                <div class="d-flex flex-row list <%= transaction.cash_flow_type == "Revenue" ? "light-green" : "light-red" %>">
                  <div class="left-col">
                    <%= transaction.date.strftime("%b %d ") %>
                  </div>
                  <div class="transaction-description">
                    <%= transaction.description %>
                    <div>
                      <a class="transaction-edit-btn" data-action="click->update-modal#updateForm">
                        <i class="fa-solid fa-pen-to-square pe-2"></i> <span class="d-none" id="propertyId"><%= @property.id %></span><span class="d-none" id="transactionId"><%= transaction.id %></span>
                      </a>
                      <%= link_to transaction_path(transaction), data: { turbo_method: :delete }, class: "transaction-delete-btn" do %>
                        <i class="fa-sharp fa-solid fa-trash"></i>
                      <% end %>
                    </div>
                  </div>
                  <% if transaction.cash_flow_type == "Revenue" %>
                    <div class="pos">
                      $<%= transaction.amount.round %> <i class="green fa-solid fa-caret-up"></i>
                    </div>
                    <% @last_count += transaction.amount.round %>
                  <% else %>
                    <div class="pos">
                      $<%= transaction.amount.round %> <i class="red fa-solid fa-caret-down"></i>
                    </div>
                    <% @last_count -= transaction.amount.round %>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          </div>
          <% unless @last.empty? %>
            <div class="summary-footer">
              <% if @last_count.negative? %>
                <div class="total light-red">
                  Net Cash Flow = -$<%= @last_count * -1 %> <i class="red fa-solid fa-caret-down ps-2"></i>
                </div>
              <% else %>
                <div class="total light-green">
                  Net Cash Flow = $<%= @last_count %> <i class="green fa-solid fa-caret-up ps-2"></i>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>


    <div class="tab-pane container active" id="current">
      <div class="row justify-content-center">
        <div class="d-flex flex-row details">
          <div class="left-col">
            <h5>Date</h5>
          </div>
          <div class="desc-col text-center">
            <h5>Description</h5>
          </div>
          <div class="amnt-col">
            <h5>Amount</h5>
          </div>
        </div>
        <div class="summary-box">
          <div class="transaction-list">
            <% @current_count = 0 %>
            <% if @current.empty? %>
              <div class="no-data">
                <p>There is no data recorded for this time period</p>
              </div>
            <% else %>
              <% @current.each do |transaction| %>
                <div class="d-flex flex-row list <%= transaction.cash_flow_type == "Revenue" ? "light-green" : "light-red" %>">
                  <div class="left-col">
                    <%= transaction.date.strftime("%b %d ") %>
                  </div>
                  <div class="transaction-description">
                    <%= transaction.description %>
                    <div>
                      <a class="transaction-edit-btn" data-action="click->update-modal#updateForm">
                        <i class="fa-solid fa-pen-to-square pe-2"></i> <span class="d-none" id="propertyId"><%= @property.id %></span><span class="d-none" id="transactionId"><%= transaction.id %></span>
                      </a>
                      <%= link_to transaction_path(transaction), data: { turbo_method: :delete }, class: "transaction-delete-btn" do %>
                        <i class="fa-sharp fa-solid fa-trash"></i>
                      <% end %>
                    </div>
                  </div>
                  <% if transaction.cash_flow_type == "Revenue" %>
                    <div class="pos">
                      $<%= transaction.amount.round %> <i class="green fa-solid fa-caret-up"></i>
                    </div>
                    <% @current_count += transaction.amount.round %>
                  <% else %>
                    <div class="pos">
                      $<%= transaction.amount.round %> <i class="red fa-solid fa-caret-down"></i>
                    </div>
                    <% @current_count -= transaction.amount.round %>
                  <% end  %>
                </div>
              <% end %>
            <% end %>
          </div>
          <% unless @current.empty? %>
            <div class="summary-footer">
              <% if @current_count.negative? %>
                <div class="total light-red">
                  Net Cash Flow = -$<%= @current_count * -1 %> <i class="red fa-solid fa-caret-down ps-2"></i>
                </div>
              <% else %>
                <div class="total light-green">
                  Net Cash Flow = $<%= @current_count %> <i class="green fa-solid fa-caret-up ps-2"></i>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>


    <div class="tab-pane container fade" id="month">
      <div class="row justify-content-center">
        <div class="d-flex flex-row details">
          <div class="left-col">
            <h5>Date</h5>
          </div>
          <div class="desc-col text-center">
            <h5>Description</h5>
          </div>
          <div class="amnt-col">
            <h5>Amount</h5>
          </div>
        </div>
        <div class="summary-box">
          <div class="transaction-list">
            <% @month_count = 0 %>
            <% if @month.empty? %>
              <div class="no-data">
                <p>There is no data recorded for this time period</p>
              </div>
            <% else %>
              <% @month.each do |transaction| %>
                <div class="d-flex flex-row list <%= transaction.cash_flow_type == "Revenue" ? "light-green" : "light-red" %>">
                  <div class="left-col">
                    <%= transaction.date.strftime("%b %d") %>
                  </div>
                  <div class="transaction-description">
                    <%= transaction.description %>
                    <div>
                      <a class="transaction-edit-btn" data-action="click->update-modal#updateForm">
                        <i class="fa-solid fa-pen-to-square pe-2"></i> <span class="d-none" id="propertyId"><%= @property.id %></span><span class="d-none" id="transactionId"><%= transaction.id %></span>
                      </a>
                      <%= link_to transaction_path(transaction), data: { turbo_method: :delete }, class: "transaction-delete-btn" do %>
                        <i class="fa-sharp fa-solid fa-trash"></i>
                      <% end %>
                    </div>
                  </div>
                  <% if transaction.cash_flow_type == "Revenue" %>
                    <div class="pos">
                      $<%= transaction.amount.round %> <i class="green fa-solid fa-caret-up"></i>
                    </div>
                    <% @month_count += transaction.amount.round %>
                  <% else %>
                    <div class="pos">
                      $<%= transaction.amount.round %> <i class="red fa-solid fa-caret-down"></i>
                    </div>
                    <% @month_count -= transaction.amount.round %>
                  <% end  %>
                </div>
              <% end %>
            <% end  %>
          </div>
          <% unless @month.empty? %>
            <div class="summary-footer">
              <% if @month_count.negative? %>
                <div class="total light-red">
                  Net Cash Flow = -$<%= @month_count * -1 %> <i class="red fa-solid fa-caret-down ps-2"></i>
                </div>
              <% else %>
                <div class="total light-green">
                  Net Cash Flow = $<%= @month_count %> <i class="green fa-solid fa-caret-up ps-2"></i>
                </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/properties/index.html.erb
<div>
  <%= render "dashboardnavbar" %>
  <div class="col-6" data-properties-target="addpropertyform">
      <%= render "addpropertyform" %>
  </div>
  <div class="container index-container">
    <div class="row d-flex mt-3">
      <div class="col-6 detailbox">
        <div class="graphing">
          <div class="indexOverview--header">
            <p class="indexOverview--headerIn">
              <h2>Overview</h2>
            </p>
          </div>
          <div class="graph bg-white rounded">
            <% data_hash = {} %>
            <% Property.all.each do |property| %>
              <% data_hash[property.address] = property.total_profit %>
            <% end %>
            <%= column_chart data_hash, title: "All Properties (Net Income)", prefix: "$", download: {background: "#ffffff"}, colors: ["#6a4c93", "#1982c4", "#8ac926", "#ffca3a", "#ff595e"] %>
          </div>
        </div>
        <div class="maping">
          <div class="indexOverview--header">
            <p class="indexOverview--headerIn">
              <h2>Properties Location</h2>
            </p>
          </div>

          <div style="width: 100%; height: 300px; border-radius: 5px;"
            data-controller="maps"
            data-maps-markers-value="<%= @markers.to_json %>"
            data-maps-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
          </div>



        </div>
      </div>

    <div class="col-6" style="position: relative">
      <%# <div class="property-blur"></div> %>
      <div class="propertybox">
        <%= render @properties %>
      </div>
    </div>
  </div>
</div>

app/views/properties/new.html.erb
    <%=  render partial:"form" %>

app/views/properties/show.html.erb
<div data-controller="transactions">
  <%= render "properties/propertynavbar", property: @property %>
  <%= render "show_content" %>
</div>