config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :properties do
    resources :transactions, only: %i[create update edit]
  end
  resources :transactions, only: :destroy
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "components", to: "pages#components"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="row m-0">
    <div class="fs-3 footer-links">
      <i class="fa-brands fa-github"></i>
      <i class="p-2 fa-brands fa-instagram"></i>
      <i class="fa-brands fa-facebook"></i>
      <div class="cr p-2">
        myPlace © 2022 Copyright. All Rights Reserved To The Boyz.
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon <%= "home-navbar" if params[:controller] == "pages" && params[:action] == "home" %>">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h1>myPlace <i class="fa-solid fa-house" id="logo"></i></h1>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Add Property", new_property_path(@property), class: "nav-link text-white"  %>
          </li>
          <li class="nav-item active">
            <%= link_to "Dashboard", properties_path, class: "nav-link text-white" %>
          </li>

          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown", controller: "toggle-class", action: "click->toggle-class#displayDrop", toggle_class_target: "toggleElement", toggle_class_active_class: "avatar--active" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "na`vbarDropdown", data: { bs_toggle: "dropdown", controller: "toggle-class", action: "click->toggle-class#displayDrop", toggle_class_target: "toggleElement", toggle_class_active_class: "avatar--active" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link btn btn-primary colo $border-radius btn-lg text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>